### ISSUE TITLE
Changing the rate for one item updates the rates for all items

### ISSUE THREAD

**Issue by super-aardvark** [Murnto/FactorioData-dlang#10]
Reproduce:

1. Select "Science Pack 3" and enter 36 u/m, click Add
2. Select "Satellite" and enter .036 u/m, click Add

Expected: Recipe View and Ratio View show results for 36 Science Pack 3 per minute, and .036 Satellite per minute.
Actual: Recipe View and Ratio View show results for .036 Science Pack 3 per minute and .036 Satellite per minute.

Checking "Lock Speed" prevents this from happening in Recipe View, but has no effect on Ratio View, causing the two to be out of sync.

**Comment by Murnto** [comment]
Unfortunately, I believe this isn't feasible to fix easily due to the original design of factoratio.

See https://github.com/Murnto/FactorioData/issues/4, you're more than welcome to submit a pull request or patch however :)
