### ISSUE TITLE
No data for Lithium perchlorate in lithium ion battery mode

### ISSUE THREAD

**Issue by tbelaire** [Murnto/FactorioData-dlang#12]
https://www.dropbox.com/s/i9wydpxnoae5ctg/Screenshot%202017-07-23%2010.37.25.png?dl=0

There's no number of electroayzers needed.

**Comment by Murnto** [comment]
This appears to be due to a poor assumption that a recipes id/name must be the same as it's primary result.
https://github.com/Murnto/FactorioData-dlang/blob/1a9c4e9c0d89821585fb35e81647583d2a3f5ef8/source/factoratio.d#L69

**Comment by Murnto** [comment]
3c007ce and Murnto/factoratio@a90deca contain recipe improvements in general for factoratio.
However, factoratio's recipe handling definitely could still be greatly improved.
