### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Xuerian** [Murnto/FactorioData-dlang#2]
Using latest DMD/vibe.d - This might be simple to fix, but my experience in D is very, very light.

`Performing "debug" build using dmd for x86.
dini 1.0.1: target for configuration "library" is up to date.
jsonizer 0.7.2: target for configuration "library" is up to date.
fact_pack ~master: building configuration "library"...
fact_pack\source\fact_pack\category_data.d(84,15): Error: cannot implicitly override base class method fact_pack.types.generic_types.BasicEnt.parse with fact_pack.types.assembling_machine.AssemblingMachine.CategoryData!().parse; add 'override' attribute
fact_pack\source\fact_pack\types\assembling_machine.d(13,5): Error: mixin fact_pack.types.assembling_machine.AssemblingMachine.CategoryData!() error instantiating
fact_pack\source\fact_pack\category_data.d(84,15): Error: cannot implicitly override base class method fact_pack.types.generic_types.BasicEnt.parse with fact_pack.types.furnace.Furnace.CategoryData!().parse; add 'override' attribute
fact_pack\source\fact_pack\types\furnace.d(12,5): Error: mixin fact_pack.types.furnace.Furnace.CategoryData!() error instantiating
fact_pack\source\fact_pack\category_data.d(84,15): Error: cannot implicitly override base class method fact_pack.types.generic_types.BasicEnt.parse with fact_pack.types.mining_drill.MiningDrill.CategoryData!().parse; add 'override' attribute
fact_pack\source\fact_pack\types\mining_drill.d(12,5): Error: mixin fact_pack.types.mining_drill.MiningDrill.CategoryData!() error instantiating
fact_pack\source\fact_pack\category_data.d(84,15): Error: cannot implicitly override base class method fact_pack.types.generic_types.BasicEnt.parse with fact_pack.types.resource.Resource.CategoryData!().parse; add 'override' attribute
fact_pack\source\fact_pack\types\resource.d(14,5): Error: mixin fact_pack.types.resource.Resource.CategoryData!() error instantiating
fact_pack\source\fact_pack\category_data.d(84,15): Error: cannot implicitly override base class method fact_pack.types.generic_types.BasicEnt.parse with fact_pack.types.accumulator.Accumulator.CategoryData!().parse; add 'override' attribute
fact_pack\source\fact_pack\types\accumulator.d(12,5): Error: mixin fact_pack.types.accumulator.Accumulator.CategoryData!() error instantiating
fact_pack\source\fact_pack\category_data.d(84,15): Error: cannot implicitly override base class method fact_pack.types.generic_types.BasicEnt.parse with fact_pack.types.steam_boiler.SteamBoiler.CategoryData!().parse; add 'override' attribute
fact_pack\source\fact_pack\types\steam_boiler.d(12,5): Error: mixin fact_pack.types.steam_boiler.SteamBoiler.CategoryData!() error instantiating
fact_pack\source\fact_pack\category_data.d(84,15): Error: cannot implicitly override base class method fact_pack.types.generic_types.BasicEnt.parse with fact_pack.types.solar_panel.SolarPanel.CategoryData!().parse; add 'override' attribute
fact_pack\source\fact_pack\types\solar_panel.d(12,5): Error: mixin fact_pack.types.solar_panel.SolarPanel.CategoryData!() error instantiating
fact_pack\source\fact_pack\category_data.d(84,15): Error: cannot implicitly override base class method fact_pack.types.generic_types.BasicEnt.parse with fact_pack.types.generator.Generator.CategoryData!().parse; add 'override' attribute
fact_pack\source\fact_pack\types\generator.d(12,5): Error: mixin fact_pack.types.generator.Generator.CategoryData!() error instantiating
dmd failed with exit code 1.`

**Comment by Murnto** [comment]
Thanks for reporting, this should be fixed in fab3460.
