### ISSUE TITLE
Ores not calculating

### ISSUE THREAD

**Issue by paranoidloyd** [Murnto/FactorioData-dlang#3]
The ore calculations appear to be broken.
http://i.imgur.com/mmshpM5.png

Also, will you be updating for .15?

**Comment by Murnto** [comment]
Thanks for reporting, this should be fixed in ca24080.

I do intend to update for 0.15 after it releases.

**Comment by paranoidloyd** [comment]
Thanks for fixing

Guess I'll have to stop being lazy and finish my calculator. 

Thanks for maintaining it while you did.
