### ISSUE TITLE
0.15 update

### ISSUE THREAD

**Issue by Cutelilduck** [Murnto/FactorioData-dlang#4]
Hello,

Do you think you will be updating this tool to 0.15? It changed a few old recipes and added several new.

**Comment by Murnto** [comment]
I plan on updating to support 0.15. Support will probably be a little hacky however, as there's no current mechanism to behave differently for different versions. So some features such as certain item categories may not work properly/at all.

**Comment by Murnto** [comment]
Main information is available from 0.15.

However, solar-panel and accumulator item categories are broken currently.
