### ISSUE TITLE
Only Stone Furnace Showing

### ISSUE THREAD

**Issue by paranoidloyd** [Murnto/FactorioData-dlang#5]
Thanks for updating so quickly!

There seems to be a bug with the furnaces and assemblers, the only ones I can select on the .15 base is the stone furnace and assembling machine 1.

**Comment by Murnto** [comment]
It appears lupa is silently failing to execute prototypes.entity.entities of the base mod fully.

**Comment by Murnto** [comment]
Should be fixed with Murnto/fact_pack@2b2e375 and Murnto/Factorio-PackGen@f6d4564.

Also fixes solar-panel and accumulator item categories.
