### ISSUE TITLE
No New Science Packs in 0.15 base

### ISSUE THREAD

**Issue by thisischrys** [Murnto/FactorioData-dlang#6]
Science packs are still assuming the old way.

**Comment by Murnto** [comment]
Could you provide more information? I haven't had the chance to actually play 0.15.

Are you referring to technologies such as Mining productivity X not listing any science packs? Or something else entirely?
What is the "new way"?

**Comment by DrMaple** [comment]
Production science packs and Science pack 3 have new recipes

Production science pack 
1x Electric Engine Unit
1x Assembling Machine 1
1x Electric Furnace

Science pack 3
1x Advanced circuit
1x Engine unit
1x Electric mining drill

**Comment by thisischrys** [comment]
These are also MORE science packs now.

**Comment by DrMaple** [comment]
All seven science packs are already in the calculator. Just wrong recipes for two of them.

**Comment by Murnto** [comment]
Fixed by updating pack data to 0.15.9.

**Comment by thisischrys** [comment]
I was talking about the included Factoratio. At least I only see Science pack 1 2 and 3?

**Comment by Murnto** [comment]
Search in Factoratio is of the start of the item name, rather than anywhere in the name as with FactorioData.

So you'll need to search Production, High Tech, etc. to find them.

**Comment by Murnto** [comment]
Murnto/factoratio@a096fcd makes Factoratio's search more similar to FactorioData's search.
