### ISSUE TITLE
[REQUEST] Allow mixed ratios

### ISSUE THREAD

**Issue by DRY411S** [Murnto/FactorioData-dlang#8]
If I say I want item X produced at 1 item per second
Then I try to add item Y at 1 item per minute
It is added but the X item per second is converted to 1 item per minute.
I'd prefer that X wasn't changed.

**Comment by Murnto** [comment]
Does the Lock Speed toggle in the top right not do what you're asking for? Admittedly, there is no explanation given of what that toggle actually does.

**Comment by DRY411S** [comment]
Yes it does. Thanks.

As you say, perhaps it needs to be explained or given a better name. Always wondered what it did. :)
