### ISSUE TITLE
Add data config: Angels + Bobs

### ISSUE THREAD

**Issue by Ramblurr** [Murnto/FactorioData-dlang#9]
It is becoming much more popular now to play Bobs with Angel's mods (petrochem, refining, and smelting etc).

It would really be great if factoratio supported the Angel data pack to help figure out ratios from all these new intermediate refining and petrochem components.

**Comment by Murnto** [comment]
I've added two new config packs, one containing Angel's mods with bare dependencies and the other containing Angel's and all of Bob's mods.

I've noticed a few localization issues on some of the technologies, namely the 'Crystallizing'/'XYZ-processing' techs, but I don't have enough time to look into it currently.

If you notice any other glaring issues, please reopen this or open a new issue.

**Comment by Ramblurr** [comment]
Awesome @Murnto! Thanks a ton :)

I can't seem to find the commit where you added the data though. Could you link me to it on github?

I want to run FactorioData locally so I use it with some of my own customizations to mods.

**Comment by Murnto** [comment]
There's no commit to add data, I just process the packs with https://github.com/Murnto/Factorio-PackGen, upload them to the server and restart. All FactorioData-dlang does is parse and present the data from Factorio-PackGen.
